var annotated_dup =
[
    [ "tr", "namespacetr.html", [
      [ "DiscreteFourierTransform", "classtr_1_1DiscreteFourierTransform.html", "classtr_1_1DiscreteFourierTransform" ],
      [ "DiscreteWaveletTransform", "classtr_1_1DiscreteWaveletTransform.html", "classtr_1_1DiscreteWaveletTransform" ],
      [ "DiscreteWaveletTransform2D", "classtr_1_1DiscreteWaveletTransform2D.html", "classtr_1_1DiscreteWaveletTransform2D" ],
      [ "FourierTransform", "classtr_1_1FourierTransform.html", "classtr_1_1FourierTransform" ],
      [ "FourierTransform2D", "classtr_1_1FourierTransform2D.html", "classtr_1_1FourierTransform2D" ],
      [ "IterativeFastFourierTransform", "classtr_1_1IterativeFastFourierTransform.html", "classtr_1_1IterativeFastFourierTransform" ],
      [ "RecursiveFastFourierTransform", "classtr_1_1RecursiveFastFourierTransform.html", "classtr_1_1RecursiveFastFourierTransform" ],
      [ "Transform", "classtr_1_1Transform.html", "classtr_1_1Transform" ]
    ] ],
    [ "TRANSFORM_MATRICES", "namespaceTRANSFORM__MATRICES.html", [
      [ "TransformMatrix", "structTRANSFORM__MATRICES_1_1TransformMatrix.html", "structTRANSFORM__MATRICES_1_1TransformMatrix" ]
    ] ],
    [ "A", "classA.html", "classA" ],
    [ "Afterdoc_Test", "classAfterdoc__Test.html", "classAfterdoc__Test" ],
    [ "Autolink_Test", "classAutolink__Test.html", "classAutolink__Test" ],
    [ "B", "classB.html", "classB" ],
    [ "C", "classC.html", "classC" ],
    [ "C1", "classC1.html", null ],
    [ "C2", "classC2.html", null ],
    [ "C3", "classC3.html", null ],
    [ "C4", "classC4.html", null ],
    [ "C5", "classC5.html", null ],
    [ "Car", "structCar.html", "structCar" ],
    [ "Compressor", "classCompressor.html", "classCompressor" ],
    [ "CoordStruct", "structCoordStruct.html", "structCoordStruct" ],
    [ "D", "classD.html", "classD" ],
    [ "Decompressor", "classDecompressor.html", "classDecompressor" ],
    [ "E", "classE.html", null ],
    [ "Enum_Test", "classEnum__Test.html", "classEnum__Test" ],
    [ "Example_Test", "classExample__Test.html", "classExample__Test" ],
    [ "Fn_Test", "classFn__Test.html", "classFn__Test" ],
    [ "HuffmanTree", "classHuffmanTree.html", "classHuffmanTree" ],
    [ "Image", "classImage.html", "classImage" ],
    [ "Include_Test", "classInclude__Test.html", "classInclude__Test" ],
    [ "Javadoc_Test", "classJavadoc__Test.html", "classJavadoc__Test" ],
    [ "Memgrp_Test", "classMemgrp__Test.html", "classMemgrp__Test" ],
    [ "mux_using_with", "classmux__using__with.html", "classmux__using__with" ],
    [ "Object", "structObject.html", null ],
    [ "Overload_Test", "classOverload__Test.html", "classOverload__Test" ],
    [ "Par_Test", "classPar__Test.html", null ],
    [ "QTstyle_Test", "classQTstyle__Test.html", "classQTstyle__Test" ],
    [ "Signal", "classSignal.html", "classSignal" ],
    [ "SomeNiceClass", "classSomeNiceClass.html", null ],
    [ "String", "classString.html", "classString" ],
    [ "Tag", "classTag.html", "classTag" ],
    [ "Test", "classTest.html", "classTest" ],
    [ "Test< T * >", "classTest_3_01T_01_5_01_4.html", "classTest_3_01T_01_5_01_4" ],
    [ "Test< void *, 200 >", "classTest_3_01void_01_5_00_01200_01_4.html", "classTest_3_01void_01_5_00_01200_01_4" ],
    [ "Truck", "structTruck.html", "structTruck" ],
    [ "Vehicle", "structVehicle.html", "structVehicle" ]
];