Transform Library: tr::FourierTransform2D< FT > Class Template Reference
tr::FourierTransform2D< FT > Class Template Reference
Represents a 2D Fourier transform operation.
#include <FourierTransform2D.hpp>
Classes
class InputSpace
Represents the input space for the 2D Fourier transform.
class OutputSpace
Represents the output space for the 2D Fourier transform.
Public Member Functions
auto compute2DFFT (Typedefs::vcpx3D &fft_coeff, const bool is_inverse) const -> void
Compute the 2D Fourier transform on a 3D complex vector.
auto get_input_space (const cv::Mat &og_image) const -> std::unique_ptr< Transform::InputSpace > override
Get the input space for the 2D Fourier transform.
auto get_output_space () const -> std::unique_ptr< Transform::OutputSpace > override
Get the output space for the 2D Fourier transform.
auto operator() (Transform::InputSpace &in, Transform::OutputSpace &out, const bool inverse) const -> void override
Perform the 2D Fourier transform operation.
Public Member Functions inherited from tr::Transform< cv::Mat >
virtual ~Transform ()=default
virtual auto get_input_space (const cv::Mat &data) const -> std::unique_ptr< Transform< cv::Mat >::InputSpace >=0
Get the input space associated with the transformation.
virtual auto get_output_space () const -> std::unique_ptr< Transform< cv::Mat >::OutputSpace >=0
Get the output space associated with the transformation.
virtual auto operator() (InputSpace &input, OutputSpace &output, const bool flag) const -> void=0
Perform the transformation operation.
Detailed Description
template<class FT>
requires std::is_base_of_v<FourierTransform, FT>
class tr::FourierTransform2D< FT >
Represents a 2D Fourier transform operation.
Template Parameters
FT The type of Fourier transform to be used (must be a derived class of FourierTransform).
Definition at line 25 of file FourierTransform2D.hpp.
Member Function Documentation
compute2DFFT()
template<class FT > requires std::is_base_of_v<FourierTransform, FT> auto FourierTransform2D::compute2DFFT (Typedefs::vcpx3D & fft_coeff, const bool is_inverse) const -> void
Compute the 2D Fourier transform on a 3D complex vector.
Parameters
fft_coeff The input data as a 3D complex vector.
is_inverse A flag indicating whether to perform the inverse transform.
Definition at line 158 of file FourierTransform2D.cpp.
Referenced by tr::FourierTransform2D< FT >::operator()().
get_input_space()
template<class FT > requires std::is_base_of_v<FourierTransform, FT> auto FourierTransform2D::get_input_space (const cv::Mat & og_image) const -> std::unique_ptr<Transform::InputSpace> override virtual
Get the input space for the 2D Fourier transform.
Parameters
og_image The original input image.
Returns
A unique pointer to the InputSpace object.
Implements tr::Transform< cv::Mat >.
Definition at line 184 of file FourierTransform2D.cpp.
References tr::utils::next_power_of_2().
get_output_space()
template<class FT > requires std::is_base_of_v<FourierTransform, FT> auto FourierTransform2D::get_output_space override virtual
Get the output space for the 2D Fourier transform.
Returns
A unique pointer to the OutputSpace object.
Implements tr::Transform< cv::Mat >.
Definition at line 201 of file FourierTransform2D.cpp.
operator()()
template<class FT > requires std::is_base_of_v<FourierTransform, FT> auto FourierTransform2D::operator() (Transform::InputSpace & in, Transform::OutputSpace & out, const bool inverse) const -> void override
Perform the 2D Fourier transform operation.
Parameters
in The input space for the transformation.
out The output space for the transformation.
inverse A flag indicating whether to perform the inverse transform.
Definition at line 207 of file FourierTransform2D.cpp.
References tr::FourierTransform2D< FT >::compute2DFFT().
The documentation for this class was generated from the following files:
include/FourierTransform2D.hpp
src/FourierTransform2D.cpp